### ISSUE TITLE
Doesn't work with expand-region

### ISSUE THREAD

**Issue by CIAvash** [xuchunyang/swap-regions.el#2]
When I select regions with [expand-region](https://github.com/magnars/expand-region.el), it says "Don't have two things to transpose".

**Comment by xuchunyang** [comment]
That error message is raised by `transpose-subr-1` which is used in `swap-regions.el`, in here it means "two regions are overlapped and this is not supported". I can't give a better error message since  `transpose-subr-1` is out of my control.

More importantly, I just tried expand-region and found  `swap-regions.el` doesn't work with it, so for now, all I can say is, expand-region is not supported.  I am not sure if I can fix this, but I would like give it a try.

**Comment by xuchunyang** [comment]
Sorry, I can not fix this.
